name: Create SQS Queue via terraform and Send Message

on:
  workflow_dispatch:
  push: # Trigger on push to main branch
    branches:
      - main

jobs:
  sqs_job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      # Step 3: Configure AWS CLI
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Step 4: Check if SQS Queue Exists
      - name: Check SQS Queue
        id: check_queue
        run: |
          QUEUE_NAME="GitHubActionsQueue"
          QUEUE_URL=$(aws sqs get-queue-url --queue-name $QUEUE_NAME --output text --query QueueUrl 2>/dev/null || echo "NOT_FOUND")
          echo "QUEUE_URL=$QUEUE_URL" >> $GITHUB_ENV
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Step 5: Create SQS Queue with Terraform if Not Found
      - name: Create SQS Queue with Terraform
        if: env.QUEUE_URL == 'NOT_FOUND'
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve
          # Extract and sanitize the clean queue URL
          RAW_QUEUE_URL=$(terraform output -raw queue_url 2>/dev/null)
          echo "Raw Terraform Output: $RAW_QUEUE_URL"  # Debugging step
          
          # Use sed to remove unwanted parts and clean the URL
          QUEUE_URL=$(echo "$RAW_QUEUE_URL" | sed 's/::debug::.*//')
          
          # Check if the URL matches the expected SQS format
          if echo "$QUEUE_URL" | grep -qE '^https://sqs\..*\.amazonaws\.com/[0-9]+/.+$'; then
            echo "QUEUE_URL=$QUEUE_URL" >> $GITHUB_ENV
          else
            echo "Error: Failed to extract valid queue URL" >&2
            exit 1
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Step 6: Debug QUEUE_URL
      - name: Debug QUEUE_URL
        run: |
          echo "Extracted QUEUE_URL: $QUEUE_URL"
        env:
          QUEUE_URL: ${{ env.QUEUE_URL }}

      # Step 7: Send Message to SQS
      - name: Send Message to SQS
        run: |
          echo "Sending message to SQS Queue: $QUEUE_URL"
          aws sqs send-message \
            --queue-url "$QUEUE_URL" \
            --message-body "Hello from GitHub Actions!" \
            --delay-seconds 0
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          QUEUE_URL: ${{ env.QUEUE_URL }}
